<?php

namespace OfferBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteArticle($id){
        $query = $this
            ->createQueryBuilder('a')
            ->delete('OfferBundle:Article', 'a')
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        return $query->execute();
    }

    public function paginationArticles($offset, $limit, $category){
        $query = $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.category = :category')
            ->setParameter('category', $category)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery();
        return $query->execute();
    }

    public function getArticlesCount(){
        $query = $this
            ->createQueryBuilder('a')
            ->select('a.id')
            ->getQuery();
        return $query->execute();
    }
}
