<?php

namespace OfferBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCities($category){
        $query = $this
            ->createQueryBuilder('c')
            ->select('c')
            ->join('c.articles', 'a')
            ->join('a.category', 'd')
            ->addSelect('a')
            ->where('d.name = :category')
            ->setParameter('category', $category)
            ->getQuery();
        return $query->execute();
    }
}
