<?php

namespace OfferBundle\Repository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteImage($id){
        $query = $this
            ->createQueryBuilder('i')
            ->delete('OfferBundle:Image', 'i')
            ->where('i.id = :id')
            ->setParameter('id', $id)
            ->getQuery();
        return $query->execute();
    }
}
